language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
  - openjdk7

install: cd zap-maven-plugin-parent && mvn install -DskipTests=true -q
script: cd zap-maven-plugin-parent && mvn verify -B -q
